server.port=3005
spring.application.name=bff

# URLs de los microservicios
microservicios.usuarios.url=http://localhost:3004
microservicios.mascotas.url=http://localhost:3001
microservicios.geolocalizacion.url=http://localhost:3002
microservicios.motor.url=http://localhost:3003

# Deshabilitar compresion para evitar conflictos con el proxy de Vite
server.compression.enabled=false

# Deshabilitar chunked encoding en respuestas del proxy
spring.mvc.async.request-timeout=30000
